### ISSUE TITLE
Export routes to kernel

### ISSUE THREAD

**Issue by fbrandstetter** [osrg/gobgp#1238]
Hello,

Currently trying to use GoBGPD for my global network - although facing some issues. How do I go about exporting prefixes from my sessions to the local machines kernel? Thought zebra would do the trick so installed it and configured it like that:

`[zebra]
    [zebra.config]
        enabled = true
        url = "unix:/var/run/quagga/zserv.api"`

Although this doesn't have any effect and I don't see the routes in kernel.

**Comment by ishidawataru** [comment]
Could you paste log here?

**Comment by frozon** [comment]
You need to specify the redistribute list for zebra too. I'm using this config for gobgpd zebra section
```yaml
zebra:
  config:
    enabled: true
    url: unix:/var/run/zserv.api
    redistribute-route-type-list:
      - kernel
```
