### ISSUE TITLE
Feature Request: Send BMP post policy

### ISSUE THREAD

**Issue by mstrother** [osrg/gobgp#1241]
BMP supports post or pre-policy routes. Currently GoBGP only support BMP pre-policy. It would be useful to have GoBGP support both pre and post-policy.  This would be specified in the configuration.

[bmp-servers.config]
    address = "127.0.0.1"
    port=11019
    post-policy=true

**Comment by ishidawataru** [comment]
It's actually supported.
Not documented though.

Please try the below.

```toml
[bmp-servers.config]
address = "127.0.0.1"
port=11019
 route-monitoring-policy = "post-policy"
```
