### ISSUE TITLE
Dynamic neighbors

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#1283]
Hey!

When GoBGP acts as a route reflector, it would be convenient if it accepted any neighbors (or any neighbors in some subnet). This way, neighbors don't have to be pre-declared.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/commit/d75edf18d7febd3f687393e8b0707e57438931eb

Can you try the latest?

**Comment by vincentbernat** [comment]
Hummm, doesn't work for me. I am using this configuration:

```yaml
global:
  config:
    as: 65000
    router-id: 1.0.0.2
    local-address-list:
      - 198.51.100.226
peer-groups:
  - config:
      peer-group-name: rr-client
      peer-as: 65000
    route-reflector:
      config:
        route-reflector-client: true
        route-reflector-cluster-id: 198.51.100.226
    add-paths:
      config:
        receive: true
        send-max: 8
dynamic-neighbors:
  - config:
      peer-group: rr-client
      prefix: 198.51.100.128/25
```

And when opening a session, I get:

```json
{"level":"info","msg":"gobgpd started","time":"2017-06-19T16:20:35+02:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2017-06-19T16:20:35+02:00"}
{"level":"info","msg":"PeerGroup rr-client is added","time":"2017-06-19T16:20:35+02:00"}
{"Name":"rr-client","Topic":"Peer","level":"info","msg":"Add a peer group configuration","time":"2017-06-19T16:20:35+02:00"}
{"level":"info","msg":"Dynamic Neighbor 198.51.100.128/25 is added to PeerGroup rr-client","time":"2017-06-19T16:20:35+02:00"}
{"Key":"198.51.100.201","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Peer Up","time":"2017-06-19T16:20:35+02:00"}
{"Key":"198.51.100.201","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","error":"Address-family rf 65537 not avalible for session","level":"warning","msg":"malformed BGP update message","time":"2017-06-19T16:20:35+02:00"}
{"Code":0,"Data":null,"Key":"198.51.100.201","State":"BGP_FSM_ESTABLISHED","Subcode":0,"Topic":"Peer","level":"warning","msg":"sent notification","time":"2017-06-19T16:20:35+02:00"}
{"Key":"198.51.100.201","Reason":"notification-sent code 0(undefined) subcode 0(undefined)","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2017-06-19T16:20:35+02:00"}
```

The same configuration with neighbors work:

```yaml
global:
  config:
    as: 65000
    router-id: 1.0.0.2
    local-address-list:
      - 198.51.100.226
neighbors:
  - config:
      neighbor-address: 198.51.100.201
      peer-as: 65000
    route-reflector:
      config:
        route-reflector-client: true
        route-reflector-cluster-id: 198.51.100.226
    add-paths:
      config:
        receive: true
        send-max: 8
```
