### ISSUE TITLE
Can't use gobgpd with ipv6 disabled

### ISSUE THREAD

**Issue by bzub** [osrg/gobgp#1303]
Hi. Does gobgpd support running the apiServer with ipv6 disabled?

```bash
/ # gobgp global as 44444 router-id 10.2.247.32
rpc error: code = Unknown desc = listen tcp6 [::]:179: socket: address family not supported by protocol
```
```bash
/ # cat /gobgpd.conf
global:
    config:
        as: 44444
        router-id: 10.2.247.60
neighbors:
    - config:
        neighbor-address: 10.2.247.32
        peer-as: 44444

/ # gobgpd -f /gobgpd.conf -t yaml -p
INFO[0000] gobgpd started
INFO[0000] Finished reading the config file              Topic=Config
FATA[0000] failed to set global config: listen tcp6 [::]:179: socket: address family not supported by protocol
```

**Comment by ishidawataru** [comment]
try

```
$  gobgp global as 44444 router-id 10.2.247.32 listen-addresses 0.0.0.0
```

or 

```yaml
global:
    config:
        as: 44444
        router-id: 10.2.247.60
        local-address-list:
        - 0.0.0.0
neighbors:
    - config:
        neighbor-address: 10.2.247.32
        peer-as: 44444
```
