### ISSUE TITLE
Help configuring gobgpd.conf for BGP confederation

### ISSUE THREAD

**Issue by openbsod** [osrg/gobgp#1428]
Hi!

GoBGP and asr9k, I`m trying to establish bgp confederation session.

On the gobgp side I see "malformed BGP update message" in syslog.
Asr shows "invalid or corrupt AS path".

ibgp session, /31, separate vlan

gobgp conf https://pastebin.com/azVBrpqC
asr conf https://pastebin.com/r95MVSm2

Session becomes Established on 12 sec and drops down.

 I look into code [bgp_configs.go](https://github.com/osrg/gobgp/blob/master/config/bgp_configs.go) but can`t find proper example of syntax  for this case ( following the patterns with [configuration.md](https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md)  )

Please help. Thank you in advance.

**Comment by fujimoto-s** [comment]
I guess you use an older version of GoBGP, because the syntax of your config file is little bit old.
Could you try with the latest version of GoBGP, v1.23?

The config for GoBGP v1.23 is like this:
```toml
[global.config]                                                                                                       
  as = 65223
  router-id = "10.215.3.19"
 
[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.215.3.18"
    peer-as = 65221
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
 
[global.apply-policy.config]
    import-policy-list = ["policy1"]
    default-import-policy = "accept-route"
    
[[defined-sets.neighbor-sets]]
  neighbor-set-name = "all_neighbors"
  neighbor-info-list = [ "10.215.3.18" ]
 
[[policy-definitions]]
  name = "policy1"
  [[policy-definitions.statements]]
    name = "statement1"
    [policy-definitions.statements.conditions.match-neighbor-set]
      neighbor-set = "all_neighbors"
    [policy-definitions.statements.actions]
      route-disposition = "reject-route"

```
