### ISSUE TITLE
Multi-VRF neighbor support

### ISSUE THREAD

**Issue by leonshaw** [osrg/gobgp#1565]
Currently it seems a neighbor can be associated to one VRF only. How to advertise routes from multiple VRFs to the same neighbor?

**Comment by iwaseyusuke** [comment]
Hi @leonshaw 

It might be depending on what you want to do though, how about configuring RT(s) per VRF?

For example,

```bash
# Configure VRFs with RT
r1> gobgp vrf add blue rd 65000:100 rt both 65000:100
r1> gobgp vrf add red  rd 65000:200 rt both 65000:200
r1> gobgp vrf
  Name                 RD                   Import RT            Export RT            ID   
  blue                 65000:100            65000:100            65000:100            0    
  red                  65000:200            65000:200            65000:200            0    

# Advertise routes with RT
r1> gobgp global rib add -a vpnv4 10.1.1.0/24 label 100 rd 65000:100 rt 65000:100
r1> gobgp global rib add -a vpnv4 10.2.1.0/24 label 200 rd 65000:200 rt 65000:200
r1> gobgp global rib -a vpnv4
   Network               Labels     Next Hop             AS_PATH              Age        Attrs
*> 65000:100:10.1.1.0/24 [100]      0.0.0.0                                   00:00:09   [{Origin: ?} {Extcomms: [65000:100]}]
*> 65000:200:10.2.1.0/24 [200]      0.0.0.0                                   00:00:06   [{Origin: ?} {Extcomms: [65000:200]}]

# Confirm routes on neighbor
r2> gobgp global rib -a vpnv4
   Network               Labels     Next Hop             AS_PATH              Age        Attrs
*> 65000:100:10.1.1.0/24 [100]      10.0.0.1             65001                00:00:19   [{Origin: ?} {Extcomms: [65000:100]}]
*> 65000:200:10.2.1.0/24 [200]      10.0.0.1             65001                00:00:16   [{Origin: ?} {Extcomms: [65000:200]}]
```

**Comment by leonshaw** [comment]
@iwaseyusuke Thanks. Is there an example of ipv4-unicast? And also want r2 to import routes to different VRF RIBs instead of global RIB.

**Comment by iwaseyusuke** [comment]
@leonshaw 

Well, `ipv4-unicast` routes on VRFs should represent `vpnv4-unicast` routes on global RIB.

You mean like the following?

```bash
# Create VRFs and add routes via "vrf" command
r1> gobgp vrf add blue rd 65000:100 rt both 65000:100
r1> gobgp vrf add red  rd 65000:200 rt both 65000:200
r1> gobgp vrf blue rib add -a ipv4 10.1.1.0/24
r1> gobgp vrf red  rib add -a ipv4 10.2.1.0/24
r1> gobgp global rib -a vpnv4
   Network               Labels     Next Hop             AS_PATH              Age        Attrs
*> 65000:100:10.1.1.0/24 [0]        0.0.0.0                                   00:00:04   [{Origin: ?} {Extcomms: [65000:100]}]
*> 65000:200:10.2.1.0/24 [0]        0.0.0.0                                   00:00:05   [{Origin: ?} {Extcomms: [65000:200]}]

# To extract only interested routes, please create VRF on r2
r2> gobgp vrf add blue rd 65000:100 rt both 65000:100
r2> gobgp vrf blue rib -a ipv4
   Network              Next Hop             AS_PATH              Age        Attrs
   10.1.1.0/24          10.0.0.1                                  00:00:16   [{Origin: ?} {LocalPref: 100}]
```

In addition, if you don't want to receive routes in which not interested, please enable RTC family like;

```toml
[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.2"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv6-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"     # <---
```

With this option, r1 will send only routes which bound to RT of r2's VRF.

```bash
# No route on r1's VRF "red"
r2> gobgp global rib -a vpnv4
   Network               Labels     Next Hop             AS_PATH              Age        Attrs
*> 65000:100:10.1.1.0/24 [0]        10.0.0.1                                  00:00:41   [{Origin: ?} {LocalPref: 100} {Extcomms: [65000:100]}]
```
