### ISSUE TITLE
Match on `next-hop`

### ISSUE THREAD

**Issue by urban-1** [osrg/gobgp#1597]
Hi all,

I am new to GoBGP and I have a question regarding policies.

I would like to match on the routes' next-hop. From what I see in the code I can use `next-hop-in-list`, however there is no example for it... Would the following be correct? (might worth updating `docs/sources/configuration.md` too)

```
  ...
  - conditions:
      bgp-conditions:
        next-hop-in-list:
          - 10.10.10.10
          - 10.10.10.15
  ...
```

Now, as a follow-up question, can we have a prefix-set in the next hop list? In my current scenario I don't need more than one IPs but it would be a lot easier to read and verify if instead of `10.10.10.10` you saw `next-hop-in-list: [ "PS-router0-Lo103" ]`

Any help/advise would be appreciated :)
