### ISSUE TITLE
RTC for Route Reflector doesn't filter routes

### ISSUE THREAD

**Issue by marcin-ptaszynski** [osrg/gobgp#1643]
Confirmed fix for issue #1630 , and after applying new version looping doesn't happen, however it seems RTC is not successfully applied and routes get distributed despite proper configuration.

Scenario:

rr-config:
```
global:
  config:
    as: 64512
    router-id: 192.168.80.221
  apply-policy:
    config:
        import-policy-list: []
        default-import-policy: accept-route
        export-policy-list: []
        default-export-policy: accept-route

neighbors:
- config:
    neighbor-address: 172.19.0.1
    peer-as: 64512
  route-reflector:
    config:
      route-reflector-client: true
      route-reflector-cluster-id: 192.168.80.221
  afi-safis:
  - config:
      afi-safi-name: l3vpn-ipv4-unicast
      enabled: true
  - config:
      afi-safi-name: rtc
      enabled: true
- config:
    neighbor-address: 172.19.63.253
    peer-as: 64512
  route-reflector:
    config:
      route-reflector-client: true
      route-reflector-cluster-id: 192.168.80.221
  afi-safis:
  - config:
      afi-safi-name: l3vpn-ipv4-unicast
      enabled: true
  - config:
      afi-safi-name: rtc
      enabled: true
```
172.19.0.1 config:

```
global:
  apply-policy:
    config: {}
  config:
    as: 64512
    router-id: 172.19.0.1

neighbors:
  - add-paths:
    config:
      receive: false
    afi-safis:
    - config:
        afi-safi-name: l3vpn-ipv4-unicast
        enabled: true
      long-lived-graceful-restart:
        config:
          enabled: true
          restart-time: 172800
      mp-graceful-restart:
        config:
          enabled: true
    - config:
        afi-safi-name: rtc
        enabled: true
      long-lived-graceful-restart:
        config: {}
      mp-graceful-restart:
        config: {}
    config:
      neighbor-address: 192.168.80.221
      peer-as: 64512
    graceful-restart:
      config:
        enabled: true
        long-lived-enabled: true
    route-reflector:
      config: {}
```
then run:
```
gobgp vrf add 1 id 1 rd 111:111 rt both 111:111
gobgp vrf add 2 id 2 rd 222:222 rt both 222:222
gobgp vrf 1 rib add 11.11.11.0/24 nexthop 1.1.1.1
gobgp vrf 2 rib add 22.22.22.0/24 nexthop 2.2.2.2
```

172.19.63.253 config:
```
global:
  apply-policy:
    config: {}
  config:
    as: 64512
    router-id: 172.19.63.253

neighbors:
  - add-paths:
    config:
      receive: false
    afi-safis:
    - config:
        afi-safi-name: l3vpn-ipv4-unicast
        enabled: true
      long-lived-graceful-restart:
        config:
          enabled: true
          restart-time: 172800
      mp-graceful-restart:
        config:
          enabled: true
    - config:
        afi-safi-name: rtc
        enabled: true
      long-lived-graceful-restart:
        config: {}
      mp-graceful-restart:
        config: {}
    config:
      neighbor-address: 192.168.80.221
      peer-as: 64512
    graceful-restart:
      config:
        enabled: true
        long-lived-enabled: true
    route-reflector:
      config: {}
```
then run:
```
gobgp vrf add 2 id 2 rd 222:222 rt both 222:222
gobgp vrf add 3 id 3 rd 333:333 rt both 333:333
gobgp vrf 2 rib add 123.123.123.0/24 nexthop 23.23.23.23
gobgp vrf 3 rib add 33.33.33.0/24 nexthop 3.3.3.3
```

After 30 seconds, I've run `gobgp vrf 1 rib add 8.8.8.8/32 nexthop 1.1.1.1` on 172.19.0.1, but all routes were advertised.

attaching pcap files for 172.19.0.1 and 172.19.63.253:
[pcap-files.zip](https://github.com/osrg/gobgp/files/1905190/pcap-files.zip)

all nodes run same version: 1e95909785e86bdd9375b05e28863542ade3c491
cc: @kishiguro , @iwaseyusuke
