### ISSUE TITLE
Broken Peer Session when RTC capability is advertised by single Peer and Graceful Restart is enabled

### ISSUE THREAD

**Issue by marcin-ptaszynski** [osrg/gobgp#1682]
## Setup:
Having RR with config:
```
global:
  config:
    as: 64512
    router-id: 192.168.80.221
  apply-policy:
    config:
        import-policy-list: []
        default-import-policy: accept-route
        export-policy-list: []
        default-export-policy: accept-route

neighbors:
- config:
    neighbor-address: 172.19.0.1
    peer-as: 64512
  route-reflector:
    config:
      route-reflector-client: true
      route-reflector-cluster-id: 192.168.80.221
  afi-safis:
  - config:
      afi-safi-name: l3vpn-ipv4-unicast
      enabled: true
  - config:
      afi-safi-name: rtc
      enabled: true
- config:
    neighbor-address: 172.19.63.254
    peer-as: 64512
  graceful-restart:
    config:
      enabled: true
      long-lived-enabled: true
  route-reflector:
    config:
      route-reflector-client: true
      route-reflector-cluster-id: 192.168.80.221
  add-paths:
    config:
      send-max: 4
  afi-safis:
  - config:
      afi-safi-name: l3vpn-ipv4-unicast
      enabled: true
    long-lived-graceful-restart:
      config:
        enabled: true
        restart-time: 172800
    mp-graceful-restart:
      config:
        enabled: true
  - config:
      afi-safi-name: rtc
      enabled: true
- config:
    neighbor-address: 172.19.0.3
    peer-as: 64512
  graceful-restart:
    config:
      enabled: true
      long-lived-enabled: true
  route-reflector:
    config:
      route-reflector-client: true
      route-reflector-cluster-id: 192.168.80.221
  add-paths:
    config:
      send-max: 4
  afi-safis:
  - config:
      afi-safi-name: l3vpn-ipv4-unicast
      enabled: true
    long-lived-graceful-restart:
      config:
        enabled: true
        restart-time: 172800
    mp-graceful-restart:
      config:
        enabled: true
  - config:
      afi-safi-name: rtc
      enabled: true
```
and 2 connected Peers (172.19.63.254 RTC disabled, other enabled)

## Issue
while RR client on 172.19.63.254 has disabled RTC (due to #1630 ), BGP Session cannot be established, because  172.19.63.254 receives unexpected empty RTC [EOR](https://tools.ietf.org/html/rfc4724#section-2) UPDATE message. This shouldn't happen, because during capability negotiation, feature should be disabled.

```
{"Key":"192.168.80.221","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","error":"Address-family rf 65668 not available for session","level":"warning","msg":"Session will be reset due to malformed BGP update message","time":"2018-05-18T00:38:42Z"}
```
For some reason, disabling Graceful Restart on RR side, caused RTC message not to be sent. attaching pcap with Graceful Restart enabled and disabled: [rtc-gr-pcaps.zip](https://github.com/osrg/gobgp/files/2015112/rtc-gr-pcaps.zip)

I haven't checked if issue is specific to RR or VPNv4 in general

## Workaround:
1. Synchronize RTC enable/disable on both RR side and Client.

cc: @kishiguro

**Comment by iwaseyusuke** [comment]
@marcin-ptaszynski Hi,

First, could you tell us the version of your GoBGP?

> while RR client on 172.19.63.254 has disabled RTC (due to #1630 ),

This means #1630 is not yet included on your version?

And please let me make clear the conditions for reproducing.
I understood that this problem occurs when we have the inconsistent capabilities of the RTC and Graceful Restart between multiple Route Reflector.
For example, with the following topology,

```text
C1 ---------------- RR ---------------- C2
     RTC: enabled        RTC: disabled
     GR:  enabled        GR:  enabled
``` 

RR and C2 will fail to establish a connection, right?

If so, I tried to reproduce this issue on my local, but the connections (both C1-RR and RR-C2) can established.
I used the latest GoBGP (2c388e07576a8ea1d7f661387f5a7ba44bc6f01e) and the following configurations.

```toml
# C1
[global.config]
  as = 65000
  router-id = "10.0.0.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.254"
    peer-as = 65000
  [neighbors.add-paths.config]
    send-max = 8
    receive = true
  [neighbors.graceful-restart.config]
    enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
```

```toml
# RR
[global.config]
  as = 65000
  router-id = "10.0.0.254"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.1"
    peer-as = 65000
  [neighbors.add-paths.config]
    send-max = 8
    receive = true
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.0.0.0"
  [neighbors.graceful-restart.config]
    enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.2"
    peer-as = 65000
  [neighbors.add-paths.config]
    send-max = 8
    receive = true
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.0.0.0"
  [neighbors.graceful-restart.config]
    enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
  # [[neighbors.afi-safis]]
  #   [neighbors.afi-safis.config]
  #     afi-safi-name = "rtc"
  #   [neighbors.afi-safis.mp-graceful-restart.config]
  #       enabled = true
```

```toml
# C2
[global.config]
  as = 65000
  router-id = "10.0.0.2"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.254"
    peer-as = 65000
  [neighbors.add-paths.config]
    send-max = 8
    receive = true
  [neighbors.graceful-restart.config]
    enabled = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
        enabled = true
  # [[neighbors.afi-safis]]
  #   [neighbors.afi-safis.config]
  #     afi-safi-name = "rtc"
  #   [neighbors.afi-safis.mp-graceful-restart.config]
  #       enabled = true
```
