### ISSUE TITLE
gobgp cannot publish route to passive router when they are not in two-way communication

### ISSUE THREAD

**Issue by magicsong** [osrg/gobgp#2036]
@fujita i think maybe it is necessary to start a new issue. When my R1 in passive mode is 
```toml
[global.config]
  as = 65001
  router-id = "192.168.98.5"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.98.2"
    peer-as = 65000
  [neighbors.transport.config]
    passive-mode = true
  [neighbors.route-server.config]
    route-server-client = true
```
And R2
```toml
[global.config]
    as = 65000
    router-id = "192.168.98.2"
    port = -1
[[neighbors]]
    [neighbors.config]
        neighbor-address = "192.168.98.5"
        peer-as = 65001
```

The R1 receive no packet. it seems R2 will wait R1 sending some info before publish routes
