### ISSUE TITLE
CLI Feature request - allow specifying `local-as` when creating neighbor

### ISSUE THREAD

**Issue by jamesharr** [osrg/gobgp#2385]
## Feature summary:
Add `local-as N` to the `gobgp neighbor add` CLI.

## Background / use-case
I'm working on a tool for our routing lab to emulate our eBGP peers by sending the routes those peers are sending so we can test routing policy changes. My intent is to run a single GoBGP instance and use VRFs + local-as to emulate that peer and then inject routes into the VRF's RIB. Due to real world scaling limitations (RAM is cheap but not free), neighbors would only be created when needed. That means creating neighbors with a local-as set. I'd like to do this on-the-fly instead of having to reload configuration.

Long term I may use the API, but for prototype purposes, the CLI is a good stepping stone.

## References:
* See first neighbor statement in [docs/sources/configuration.md](https://github.com/osrg/gobgp/blob/master/docs/sources/configuration.md).
```toml:
    [neighbors.config]
        peer-as = 2
        auth-password = "password"
        neighbor-address = "192.168.10.2"
        # override global.config.as value
        local-as = 1000
        remove-private-as = "all"
        # To enable peer group setting, uncomment the following
        #peer-group = "my-peer-group"
```
