### ISSUE TITLE
Redistribute BGP routes into Linux kernel (FIB)

### ISSUE THREAD

**Issue by Drustan** [osrg/gobgp#2582]
Hello everyone!

I'm trying to set up GoBGP (version 3.7.0) with FRR (version 8.1) to redistribute routes learned from BGP (iBGP setup) into the Linux kernel.

Here is my GoBGP configuration :

```
root@linux_router:~# cat /etc/gobgp/gobgpd.yml
global:
    config:
        as: 65001
        router-id: 198.51.100.160
neighbors:
    - config:
        neighbor-address: 192.0.2.146
        peer-as: 65001
    - config:
        neighbor-address: 192.0.2.147
        peer-as: 65001
    - config:
        neighbor-address: 192.0.2.148
        peer-as: 65001
zebra:
    config:
        enabled: true
        url: "unix:/var/run/frr/zserv.api"
        version: 6
```

So far, so good, the sessions are established :

```
root@linux_router:~# gobgp neighbor
Peer          AS  Up/Down State       |#Received  Accepted
192.0.2.146 65001 00:39:17 Establ      |        8         8
192.0.2.147 65001 00:39:17 Establ      |        8         8
192.0.2.148 65001 00:39:14 Establ      |        8         8
```

And the routes learn from GoBGP are visible in FRR :

```
root@linux_router:~# vtysh

Hello, this is FRRouting (version 8.1).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

linux_router# sh ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

K>* 0.0.0.0/0 [0/0] via 198.51.100.1, ens192, 00:46:38
C>* 198.51.100.0/24 is directly connected, ens192, 00:46:38
B   10.42.0.0/24 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.42.1.0/24 [20/0] via 192.0.2.148 inactive, weight 1, 00:44:56
B   10.42.2.0/24 [20/0] via 192.0.2.147 inactive, weight 1, 00:44:58
B   10.43.0.1/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.0.10/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.8.100/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.9.10/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.24.247/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.227.32/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
B   10.43.233.3/32 [20/0] via 192.0.2.146 inactive, weight 1, 00:44:58
```

But unfortunately, I don't get any route in the FIB Linux kernel :

```
root@linux_router:~# ip route
default via 198.51.100.1 dev ens192 proto static
198.51.100.0/24 dev ens192 proto kernel scope link src 198.51.100.160
```

Do you guys know what I'm missing here? Also, why are the BGP routes learn from GoBGP marked as inactive in FRR?

Thanks for your help,
