### ISSUE TITLE
gobgpd with auth-password and dynamic neighbors

### ISSUE THREAD

**Issue by mikejoh** [osrg/gobgp#2589]
Hi,

i have the following setup:
- A `kind` (Kubernetes in Docker) cluster running `cilium` with the [`--enable-bgp-control-plane`](https://docs.cilium.io/en/latest/network/bgp-control-plane/#cilium-bgp-control-plane) flag set to `true`.
- `gobgpd` running `v3.7.0` in a Docker container attached to the same Docker network as the `kind` cluster are running in.

The BGP implementation in `cilium` that are feature toggled using the flag above are using `gobgp` in code. The current implementation does not allow us to set an authentication password when configuring BGP peering in `cilium`.

What i'm trying to wrap my head around is why this `gobgpd` configuration in YAML:
```
global:
  config:
    as: 65130
    router-id: 172.18.0.6
    port: 179
    local-address-list:
      - "172.18.0.6"

peer-groups:
  transport:
    config:
      local-address: "172.18.0.6"
  config:
    peer-group-name: cilium-nodes
    peer-as: 65131
    local-as: 65130
    auth-password: "password"

dynamic-neighbors:
  config:
    prefix: 172.18.0.0/16
    peer-group: cilium-nodes
```
don't yield an error stating that the `cilium` peers doesn't use authentication and still let the dynamic neighbors connect and establish connections?

Have i missed something in how this is should work? Or maybe i have overlooked something vital in how BGP works?

I'm using [this](https://github.com/mikejoh/k8s-tech-demos/tree/main/cilium-bgp-demo) part of a repository created to test this.

Thanks!
