### ISSUE TITLE
Regular Expression not Matching with Community

### ISSUE THREAD

**Issue by RajdeepMondal** [osrg/gobgp#2652]
I have a the following router configuration at startup:
```
global:
  apply-policy:
    config:
      default-import-policy: reject-route
      import-policy-list:
      - example-policy
  config:
    as: 65001
    router-id: 192.2.3.4
neighbors:
- config:
    neighbor-address: 3.0.0.3
    peer-as: 65002
  transport:
    config:
      local-address: 3.0.0.2
defined-sets:
  bgp-defined-sets:
    community-sets:
      community-list:
      - ^0:1$
      community-set-name: c1
policy-definitions:
- name: example-policy
  statements:
  - actions:
      route-disposition: accept-route
    conditions:
      bgp-conditions:
        match-community-set:
          community-set: c1
          match-set-options: any
    name: statement1
```

With this configuration if I have incoming routes that have the communities [0:1 0:12] then they are matched against statement1 of example-policy. However, this should not be the case because ^0:1$ should only match against the community [0:1]. 

To reproduce:

   1. Create a network and peer an ExaBGP with GoBGP.
   2. Configure FRR with the configuration shown above.
   3. Announce the community through ExaBGP.

Expected behavior:
    The route must be denied.

GoBGP version: 3.13.0
