### ISSUE TITLE
Prefix Set Bug?

### ISSUE THREAD

**Issue by RajdeepMondal** [osrg/gobgp#2690]
I have a router running GoBGP with the following configuration:
```
global:
  apply-policy:
    config:
      default-import-policy: reject-route
      import-policy-list:
      - example-policy
  config:
    as: 65001
    router-id: 192.2.3.4
neighbors:
- config:
    neighbor-address: 3.0.0.3
    peer-as: 65002
  transport:
    config:
      local-address: 3.0.0.2
defined-sets:
  prefix-sets:
    prefix-list:
    - ip-prefix: 96.0.0.0/5
      masklength-range: 11..17
    - ip-prefix: 96.0.0.0/6
      masklength-range: 18..32
    - ip-prefix: 102.0.0.0/7
      masklength-range: 18..32
    - ip-prefix: 101.0.0.0/8
      masklength-range: 18..32
    - ip-prefix: 100.128.0.0/9
      masklength-range: 18..32
    - ip-prefix: 100.64.0.0/10
      masklength-range: 18..32
    - ip-prefix: 100.32.0.0/11
      masklength-range: 18..32
    - ip-prefix: 100.16.0.0/12
      masklength-range: 18..32
    - ip-prefix: 100.8.0.0/13
      masklength-range: 18..32
    - ip-prefix: 0.0.0.0/0
      masklength-range: 10..10
    - ip-prefix: 128.0.0.0/1
      masklength-range: 11..11
    - ip-prefix: 0.0.0.0/2
      masklength-range: 11..11
    - ip-prefix: 64.0.0.0/3
      masklength-range: 11..11
    - ip-prefix: 112.0.0.0/4
      masklength-range: 11..11
    - ip-prefix: 104.0.0.0/5
      masklength-range: 11..11
    prefix-set-name: ps1
policy-definitions:
- name: example-policy
  statements:
  - actions:
      bgp-actions:
        set-community:
          options: remove
          set-community-method:
            communities-list:
            - '[0-2][0-2]*:[0-2][0-2]'
        set-next-hop: 97.156.64.3
      route-disposition: accept-route
    conditions:
      match-prefix-set:
        prefix-set: ps1
    name: statement1
```

I advertised the prefix **100.11.131.203/10** from an ExaBGP router to this GoBGP router. The prefix does not show up on the global RIB, meaning it is denied.

Expected behavior:
The prefix should be allowed, as it matches with the prefix **0.0.0.0/0 11...11** in the prefix set ps1.
