### ISSUE TITLE
gobgp global rib -a ipv6  many unexpected routes are displayed

### ISSUE THREAD

**Issue by LiuChengqian90** [osrg/gobgp#2813]
I want bgp to learn only the configured routes.
What should I do?

![11111](https://github.com/osrg/gobgp/assets/25579056/e9da7711-2b4a-4c87-9b20-f06aeeaf7899)

here is my conf
```toml
[global.config]
  as = 64512
  router-id = "10.56.225.214"
  local-address-list = ["10.56.226.101","fdbd:dc41:0004:0394:4200:0000:0a38:e265",]

# v4
[[peer-groups]]
  [peer-groups.config]
     peer-group-name = "tor"
     local-as = 64512
  [peer-groups.timers.config]
     hold-time = 3
     keepalive-interval = 1
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.56.226.65"
    peer-group = "tor"
  [neighbors.transport.config]
    local-address = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.192/32"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.197/32"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.196/32"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.192/29"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.192/28"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.8.0/26"
  nexthop = "10.56.226.101"
[[bgp-routes]]
  afi-safi = "ipv4-unicast"
  nlri = "33.249.1.192/26"
  nexthop = "10.56.226.101"

[[defined-sets.prefix-sets]]
 prefix-set-name = "ps1"
 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "0.0.0.0/0"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.192/32"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.197/32"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.196/32"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.192/29"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.192/28"


 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.8.0/26"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "33.249.1.192/26"

 [[defined-sets.prefix-sets.prefix-list]]
   ip-prefix = "fdbd:dc41:fe:4400::/56"

[[policy-definitions]]
   name = "policy1"
   [[policy-definitions.statements]]
     name = "statement1"
     [policy-definitions.statements.conditions.match-prefix-set]
       prefix-set = "ps1"
       match-set-options = "any"
   [policy-definitions.statements.actions]
     route-disposition = "accept-route"

[global.apply-policy.config]
 import-policy-list = ["policy1"]
 default-import-policy = "reject-route"

# v6
[[peer-groups]]
  [peer-groups.config]
     peer-group-name = "tor-ipv6"
     local-as = 64512
  [peer-groups.timers.config]
     hold-time = 3
     keepalive-interval = 1
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
[[neighbors]]
  [neighbors.config]
    neighbor-address = "fdbd:dc41:0004:0394::1"
    peer-group = "tor-ipv6"
  [neighbors.transport.config]
    local-address = "fdbd:dc41:0004:0394:4200:0000:0a38:e265"
[[bgp-routes]]
  afi-safi = "ipv6-unicast"
  nlri = "fdbd:dc41:fe:4400::/56"
  nexthop = "fdbd:dc41:0004:0394:4200:0000:0a38:e265"
```
