### ISSUE TITLE
GoBGP does not accept configuration when using remove private AS with confederation IBGP

### ISSUE THREAD

**Issue by RajdeepMondal** [osrg/gobgp#2850]
I have the following configuration for a GoBGP router:
```
global:
  config:
    router-id: 192.168.255.1
    as: 256
  confederation:
    config:
      enabled: true
      identifier: 1
      member-as-list: []
neighbors:
- config:
    neighbor-address: 3.0.0.3
    peer-as: 64512
  transport:
    config:
      local-address: 3.0.0.2
  afi-safis:
  - config:
      afi-safi-name: ipv4-unicast
- config:
    neighbor-address: 4.0.0.3
    peer-as: 256
    remove-private-as: all
  transport:
    config:
      local-address: 4.0.0.2
  afi-safis:
  - config:
      afi-safi-name: ipv4-unicast
```

When I try to start the GoBGP daemon with this configuration, I get an error message:
```bash
$ gobgpd -t yaml -f /etc/gobgp/gobgp.yml
{"Error":"can't set remove-private-as for iBGP peer","Topic":"Config","level":"fatal","msg":"Can't read config file /etc/gobgp/gobgp.yml","time":"2024-10-22T06:43:08Z"}
```

Is this expected? Because I tested a similar configuration with FRR and it gets accepted there.
Why can't I remove private ASes if I am setting up an IBGP connection with a peer?
