### ISSUE TITLE
Route accepted with invalid AS path regex

### ISSUE THREAD

**Issue by rsingha108** [osrg/gobgp#2915]
I have a router and I am trying to inject route using exabgp. The router has a inbound routing policy.

Exabgp Config:
```
process announce-routes {
    run python exabgp/example.py;
    encoder json;
}

neighbor 3.0.0.2 {                 # Remote neighbor to peer with
    router-id 3.0.0.3;              # Our local router-id
    local-address 3.0.0.3;          # Our local update-source
    local-as 40;                    # Our local AS
    peer-as 30;                     # Peer's AS

    api {
        processes [announce-routes];
    }
}
```

Announcing the route:
```
announce route 10.1.0.0/16 next-hop self local-preference 100 med 20 as-path [40 64560 64561] community [64560:200]
```

Here is the gobgp router config:

```
global:
  apply-policy:
    config:
      default-import-policy: reject-route
      import-policy-list:
      - example-policy
  config:
    as: 30
    router-id: 192.2.3.4
neighbors:
- config:
    neighbor-address: 3.0.0.3
    peer-as: 40
  transport:
    config:
      local-address: 3.0.0.2
defined-sets:
  bgp-defined-sets:
    as-path-sets:
      as-path-list:
      - '['
      as-path-set-name: a1
policy-definitions:
- name: example-policy
  statements:
  - actions:
      route-disposition: accept-route
    conditions:
      bgp-conditions:
        match-as-path-set:
          as-path-set: a1
          match-set-options: invert
    name: statement1
```

Although the as-path-regex is invalid, the router accepts the route.
