### ISSUE TITLE
How to enable multiple SAFI's?

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#342]
Hello!

Sorry for bothering you but I haven't any examples How I could specify multiple SAFI's.

I'm using this configuration:
```bash
[Global]
  [Global.GlobalConfig]
    As = 65001
    RouterId = "178.62.227.110"

[Neighbors]
  [[Neighbors.NeighborList]]
    [Neighbors.NeighborList.NeighborConfig]
      NeighborAddress = "213.133.111.200"
      PeerAs = 65001
    [Neighbors.NeighborList.AfiSafis]
      [[Neighbors.NeighborList.AfiSafis.AfiSafiList]]
        AfiSafiName = "ipv4-flowspec"
```

But IPv4-unicast safi disabled when I specified flowspec explicitly.

**Comment by ishidawataru** [comment]
```toml
[Global]
  [Global.GlobalConfig]
    As = 65001
    RouterId = "178.62.227.110"

[Neighbors]
  [[Neighbors.NeighborList]]
    [Neighbors.NeighborList.NeighborConfig]
      NeighborAddress = "213.133.111.200"
      PeerAs = 65001
    [Neighbors.NeighborList.AfiSafis]
      [[Neighbors.NeighborList.AfiSafis.AfiSafiList]]
        AfiSafiName = "ipv4-flowspec"
      [[Neighbors.NeighborList.AfiSafis.AfiSafiList]]
        AfiSafiName = "ipv4-unicast"
```
the configuration format for GoBGP is toml.
enumerate route families you want to enable like above.
