### ISSUE TITLE
Big challenge with default export filters

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#596]
Hello!

I'm using GoBGP as client for 2 BGP router servers. And I hit very_popular and ugly issue - I have reannounced all received prefixes from first uplink to the second and vice versa.

So fortunately I have filters on opposite side and I haven;t broken Internet. 

So I have multiple questions / suggestions. 

First of all, I want to ask to set default export policy to reject or just reject re-announce prefixes received from other uplink to another. 

If somebody want it it should _explicitly_ enable this.

I have achieved this with following CLI command:
```bash
gobgp global policy export set default reject    
```

But I haven't any idea how to do same with configuration file. Could you help me here?

**Comment by ishidawataru** [comment]
Hi, please try this

```toml
[global.config]
  as = 1
  router-id = "1.1.1.1"
  [global.apply-policy.config]
    default-export-policy = "reject-route"
```
