### ISSUE TITLE
OpenMessage doesn't contain AS when using `local-as`

### ISSUE THREAD

**Issue by vincentbernat** [osrg/gobgp#694]
Hey!

I am using this simple configuration:

```yaml
global:
  config:
    router-id: 192.0.2.0
neighbors:
  - config:
      neighbor-address: 192.0.2.1
      peer-as: 64512
      local-as: 65001
  - config:
      neighbor-address: 192.0.2.3
      peer-as: 64512
      local-as: 65002
```

gobgp is sending an OPEN message without the ASN.

```
    192.0.2.0.47156 > 192.0.2.1.179: Flags [P.], cksum 0x8a87 (correct), seq 1:46, ack 1, win 229, options [nop,nop,TS val 25941 ecr 60994], length 45: BGP
        Open Message (1), length: 45
          Version 4, my AS 0, Holdtime 90s, ID 192.0.2.0
          Optional parameters, length: 16
            Option Capabilities Advertisement (2), length: 14
              Route Refresh (2), length: 0
              Multiprotocol Extensions (1), length: 4
                AFI IPv4 (1), SAFI Unicast (1)
                0x0000:  0001 0001
              32-Bit AS Number (65), length: 4
                 4 Byte AS 0
                0x0000:  0000 0000
```

Looking at the code, I am unsure how this should be handled. `config/default.go` and `config/util.go` takes the local AS from global configuration only. Other files seem to use `LocalAs`.
