### ISSUE TITLE
failed to free the fsm.h.t

### ISSUE THREAD

**Issue by danielseide** [osrg/gobgp#719]
GoBGP 1.3
ExaBGP 3.4.13

I connected GoBGP with 500 Peers 500 Routes each (250 000 routes in total). The machine went out of RAM and began using swapspace (GoBGP got 3,5 GB RAM of 4 GB built in). When the swapspace reaches 1 GB at experiment time 7:30 - 8:00 minutes GoBGP crashes with following error in terminal:

{"level":"fatal","msg":"failed to free the fsm.h.t for 192.168.6.26BGP_FSM_ESTABLISHED BGP_FSM_IDLE","time":"2016-02-25T13:26:29+01:00"}

I tried this multiple times - always same behaviour.

maybe it's connected to [issue695](https://github.com/osrg/gobgp/issues/695) and [issue404](https://github.com/osrg/gobgp/issues/404)

edit:
log added: [gobgp_error.txt](https://github.com/osrg/gobgp/files/148265/gobgp_error.txt)

**Comment by ishidawataru** [comment]
Hi,

Thanks for the report! I also happened to see the same behaviour.
Will fix it and get back to you.

Are you trying with RouteServer configuration? or normal bgp configuration?

**Comment by danielseide** [comment]
normal bgp configuration:

```toml
[Global]
  [Global.Config]
    As = 65002
    RouterId = "192.168.0.25"

[Neighbors]
	[[Neighbors.NeighborList]]
		[Neighbors.NeighborList.Config]
			NeighborAddress = "192.168.5.21"
			PeerAs = 65001
		[Neighbors.NeighborList.Timers.Config]
			holdtime = 180

	[[Neighbors.NeighborList]]
		[Neighbors.NeighborList.Config]
			NeighborAddress = "192.168.5.22"
			PeerAs = 65001
		[Neighbors.NeighborList.Timers.Config]
			holdtime = 180

    ...
```
